### ISSUE TITLE
Allow using a different name for collecting

### ISSUE THREAD

**Issue by tmccombs** [TBRSS/serapeum#3]
I would like a way to specify a different name for the collect function in the collecting macro. This would be useful in scenarios where you have nested collecting macros, or want to call the collect method inside an iterate:iter form.

**Comment by ruricolist** [comment]
I have been thinking about a macro for named collectors for a while, but it's not something I use myself so I'm not sure what the syntax should be.

One possibility would be something simple like `with-collectors`, where you name the collectors and the lists are returned as multiple values.

Another possibility is to assimilate the `collect` macro from CMUCL, the self proclaimed "ultimate collection macro", which is apparently useful enough to have made it into the code of most every Lisp implementation. E.g., [SBCL](https://github.com/sbcl/sbcl/blob/master/src/code/early-extensions.lisp#L248).

One concern I have is that `collecting` in Serapeum has different semantics than most classical collecting macros; the collector is bound to a function instead of a macro, so it can escape the `collecting` form. I'm not sure that would be the right thing for a more general collecting macro.

Any thoughts?

**Comment by ruricolist** [comment]
Some prior art:

Cliki: http://www.cliki.net/COLLECTING

Discussion on comp.lang.lisp (2001): https://groups.google.com/forum/#!msg/comp.lang.lisp/I8KpggxO-P4/9O5M81Raef0J

**Comment by ruricolist** [comment]
One more consideration: I would like to avoid, as much as possible, package conflicts with Iterate. (This is why Serapeum no longer exports some trivial collection macros like `minimizing`, `maximizing`, and so forth).

Of course Iterate itself is also quite a nice general-purpose collection macro:

```

(defmacro iterating (&body body)
  `(iterate (repeat 1)
     ,@(butlast body)
     (finally (return ,(car (last body))))))

(iterating
  (collect 1 into xs)
  (collect 2 into ys)
  (values xs ys))
;; => '(1) '(2)
```

**Comment by ruricolist** [comment]
I've added simple `with-collector` and `with-collectors` macros. They're easy to understand, and since `collecting` can be defined in terms of `with-collector`, they don't require special maintenance.
